CREATE DATABASE CarSaleDB;
GO

USE CarSaleDB;
GO

CREATE TABLE Brand (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Customer (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Mobile VARCHAR(15) NOT NULL
);

CREATE TABLE Car (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    BrandId INT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    Price DECIMAL(18,2) NOT NULL, 
    
    FOREIGN KEY (BrandId) REFERENCES Brand(Id)
);

CREATE TABLE SaleOrder (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerId INT NOT NULL,
    CarId INT NOT NULL,
    OrderDate DATETIME DEFAULT GETDATE(), 
    
    FOREIGN KEY (CustomerId) REFERENCES Customer(Id),
    FOREIGN KEY (CarId) REFERENCES Car(Id)
);